// TanStack adapter: Router/Start integration
//
// Handles:
//   - File-based route generation for TanStack Router
//   - Route tree generation from src/routes/
//   - Code splitting per route
//   - Type-safe route links
//   - TanStack Start SSR manifest

use anyhow::Result;
use std::path::{Path, PathBuf};

/// TanStack adapter configuration
pub struct TanStackAdapter {
    /// Project root
    pub root: PathBuf,
    /// Routes directory (default: src/routes)
    pub routes_dir: PathBuf,
    /// Detected routes
    pub routes: Vec<TanStackRoute>,
}

#[derive(Debug, Clone)]
pub struct TanStackRoute {
    /// Route path (e.g., "/", "/about", "/posts/$id")
    pub path: String,
    /// File path relative to project root
    pub file: String,
    /// Route name (derived from file path)
    pub name: String,
    /// Parent route path (for nesting)
    pub parent: Option<String>,
    /// Dynamic params (e.g., ["$id"])
    pub params: Vec<String>,
    /// Is this a layout route
    pub is_layout: bool,
}

impl TanStackAdapter {
    pub fn new(root: &Path) -> Self {
        let routes_dir = root.join("src").join("routes");
        Self {
            root: root.to_path_buf(),
            routes_dir,
            routes: Vec::new(),
        }
    }

    /// Discover all routes from src/routes/
    pub fn discover_routes(&mut self) -> Result<()> {
        if !self.routes_dir.exists() || !self.routes_dir.is_dir() {
            return Ok(());
        }
        let routes_dir = self.routes_dir.clone();
        self.scan_routes(&routes_dir, "")?;
        Ok(())
    }

    fn scan_routes(&mut self, dir: &Path, prefix: &str) -> Result<()> {
        let entries = std::fs::read_dir(dir)?;

        for entry in entries {
            let entry = entry?;
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().to_string();

            if path.is_dir() {
                // Nested route directory
                let route_segment = if name.starts_with('$') {
                    // Dynamic param: $id → :id
                    name.clone()
                } else {
                    name.clone()
                };
                let new_prefix = if prefix.is_empty() {
                    format!("/{}", route_segment)
                } else {
                    format!("{}/{}", prefix, route_segment)
                };
                self.scan_routes(&path, &new_prefix)?;
            } else if name.ends_with(".tsx") || name.ends_with(".ts") {
                let stem = name.split('.').next().unwrap_or(&name);
                let (route_path, is_layout, params) = match stem {
                    "__root" | "root" => ("/".to_string(), true, Vec::new()),
                    "index" => (if prefix.is_empty() { "/".to_string() } else { prefix.to_string() }, false, Vec::new()),
                    _ => {
                        // Check for layout
                        let is_layout = stem == "layout" || stem.ends_with(".layout");
                        // Dynamic param
                        let mut params: Vec<String> = Vec::new();
                        let seg = if stem.starts_with('$') {
                            params.push(stem.to_string());
                            format!(":{}", &stem[1..])
                        } else {
                            stem.to_string()
                        };
                        let path = if prefix.is_empty() {
                            format!("/{}", seg)
                        } else {
                            format!("{}/{}", prefix, seg)
                        };
                        (path, is_layout, params)
                    }
                };

                let file_rel = path.strip_prefix(&self.root).unwrap_or(&path).to_string_lossy().to_string();
                let route_name = stem.replace('$', "").replace('-', "_");

                self.routes.push(TanStackRoute {
                    path: route_path,
                    file: file_rel,
                    name: route_name,
                    parent: if prefix.is_empty() { None } else { Some(prefix.to_string()) },
                    params,
                    is_layout,
                });
            }
        }

        Ok(())
    }

    /// Generate TanStack Router route tree code
    pub fn generate_route_tree(&self) -> String {
        let mut code = String::new();
        code.push_str("// Auto-generated by Pledge TanStack adapter\n");
        code.push_str("// TanStack Router route tree\n\n");

        // Import all route files
        for route in &self.routes {
            let import_path = format!("/{}", route.file.replace('\\', "/"));
            code.push_str(&format!(
                "const {}Route = lazyRouteComponent(() => import('{}'));\n",
                route.name, import_path
            ));
        }

        code.push_str("\n");

        // Build route tree
        code.push_str("export const routeTree = {\n");
        for route in &self.routes {
            code.push_str(&format!(
                "  '{}': {{\n    component: {}Route,\n    path: '{}',\n    isLayout: {},\n  }},\n",
                route.path, route.name, route.path, route.is_layout
            ));
        }
        code.push_str("};\n\n");

        // Generate router setup
        code.push_str(r#"export function createRouter() {
  return {
    routes: routeTree,
    navigate(path) {
      const route = routeTree[path];
      if (route) {
        route.component().then(mod => {
          const app = document.getElementById('root');
          if (app && mod.default) {
            app.innerHTML = '';
            mod.default(app);
          }
        });
      }
    }
  };
}
"#);

        code
    }

    /// Generate type-safe route links manifest
    pub fn generate_route_manifest(&self) -> String {
        let manifest: Vec<serde_json::Value> = self.routes.iter().map(|r| {
            serde_json::json!({
                "path": r.path,
                "file": r.file,
                "name": r.name,
                "parent": r.parent,
                "params": r.params,
                "isLayout": r.is_layout,
            })
        }).collect();

        serde_json::to_string_pretty(&manifest).unwrap_or("[]".to_string())
    }
}
