// PledgeStack adapter: React frontend + Rust backend
//
// Handles:
//   - app/ directory routing (React .tsx pages, like Next.js App Router)
//   - server/ directory for Rust backend (.rs or .psx files)
//   - API routes from server/api/*.rs or server/api/*.psx
//   - Middleware from server/middleware/*.rs or *.psx
//   - Route manifest generation
//   - .psx -> .rs copy for cargo build compatibility
//   - Frontend SSR/SSG detection
//
// File conventions:
//   app/page.tsx              -> GET /          (React page)
//   app/about/page.tsx        -> GET /about     (React page)
//   app/blog/[slug]/page.tsx  -> GET /blog/:slug (dynamic route)
//   server/api/users.rs       -> /api/users     (Rust API handler)
//   server/api/users.psx      -> /api/users     (PledgeStack API handler)
//   server/middleware/auth.rs -> auth middleware (applies to all routes)
//   server/lib.rs             -> server entry point

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// PledgeStack adapter configuration
pub struct PledgeStackAdapter {
    /// Project root
    pub root: PathBuf,
    /// Detected frontend routes (from app/)
    pub frontend_routes: Vec<FrontendRoute>,
    /// Detected backend routes (from server/)
    pub backend_routes: Vec<BackendRoute>,
    /// Detected middleware
    pub middleware: Vec<MiddlewareEntry>,
    /// Server entry point file (if any)
    pub server_entry: Option<PathBuf>,
}

/// A frontend route (React page)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrontendRoute {
    /// URL path (e.g., "/", "/about", "/blog/:slug")
    pub path: String,
    /// File path relative to project root
    pub file: String,
    /// Dynamic segments (e.g., ["slug"] for /blog/[slug])
    pub params: Vec<String>,
    /// Whether this page supports SSR
    pub ssr: bool,
    /// Whether this page is static (SSG)
    pub static_gen: bool,
}

/// A backend route (Rust API handler)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BackendRoute {
    /// HTTP method (GET, POST, PUT, DELETE, PATCH)
    pub method: String,
    /// URL path (e.g., "/api/users", "/api/users/:id")
    pub path: String,
    /// File path relative to project root
    pub file: String,
    /// Function name in the Rust source
    pub handler: String,
    /// File extension type
    pub ext: BackendExt,
    /// Dynamic segments (e.g., ["id"] for /api/users/[id])
    pub params: Vec<String>,
}

/// Middleware entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MiddlewareEntry {
    /// File path relative to project root
    pub file: String,
    /// Middleware name (derived from filename)
    pub name: String,
    /// File extension type
    pub ext: BackendExt,
    /// Routes this middleware applies to (empty = all)
    pub applies_to: Vec<String>,
}

/// Supported backend file extensions
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum BackendExt {
    /// Standard Rust file
    Rs,
    /// PledgeStack extension (treated as Rust, copied to .rs for build)
    Psx,
}

impl BackendExt {
    /// All supported extensions
    pub const ALL: &[&str] = &["rs", "psx"];

    /// Parse from file extension
    pub fn from_ext(ext: &str) -> Option<Self> {
        match ext.to_lowercase().as_str() {
            "rs" => Some(Self::Rs),
            "psx" => Some(Self::Psx),
            _ => None,
        }
    }
}

/// Route manifest generated by the adapter
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouteManifest {
    /// Frontend routes
    pub frontend: Vec<FrontendRoute>,
    /// Backend routes
    pub backend: Vec<BackendRoute>,
    /// Middleware
    pub middleware: Vec<MiddlewareEntry>,
    /// Server entry point (relative path, if any)
    pub server_entry: Option<String>,
}

impl PledgeStackAdapter {
    /// Create a new adapter for the given project root
    pub fn new(root: &Path) -> Self {
        Self {
            root: root.to_path_buf(),
            frontend_routes: Vec::new(),
            backend_routes: Vec::new(),
            middleware: Vec::new(),
            server_entry: None,
        }
    }

    /// Discover all routes -- both frontend (app/) and backend (server/)
    pub fn discover(&mut self) -> Result<()> {
        self.discover_frontend_routes()?;
        self.discover_backend_routes()?;
        self.discover_middleware()?;
        self.discover_server_entry()?;
        Ok(())
    }

    /// Scan app/ directory for React frontend routes
    fn discover_frontend_routes(&mut self) -> Result<()> {
        let app_dir = self.root.join("app");
        if !app_dir.exists() || !app_dir.is_dir() {
            return Ok(());
        }
        self.scan_app_directory(&app_dir, "")?;
        Ok(())
    }

    /// Recursively scan app/ directory for page.tsx files
    fn scan_app_directory(&mut self, dir: &Path, prefix: &str) -> Result<()> {
        let entries = std::fs::read_dir(dir)
            .with_context(|| format!("Failed to read app directory: {}", dir.display()))?;

        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().to_string();

            if path.is_dir() {
                if name.starts_with('_') {
                    continue;
                }
                let route_segment = if name.starts_with('[') && name.ends_with(']') {
                    let param = name[1..name.len() - 1].to_string();
                    format!(":{}", param)
                } else {
                    name.clone()
                };
                let new_prefix = if prefix.is_empty() {
                    format!("/{}", route_segment)
                } else {
                    format!("{}/{}", prefix, route_segment)
                };
                self.scan_app_directory(&path, &new_prefix)?;
            } else if path.is_file() {
                if name == "page.tsx" || name == "page.jsx" || name == "page.ts" {
                    let route_path = if prefix.is_empty() {
                        "/".to_string()
                    } else {
                        prefix.to_string()
                    };
                    let params = extract_params(&route_path);
                    let rel_file = path
                        .strip_prefix(&self.root)
                        .unwrap_or(&path)
                        .to_string_lossy()
                        .replace('\\', "/");
                    let (ssr, static_gen) = detect_render_mode(&path);
                    self.frontend_routes.push(FrontendRoute {
                        path: route_path,
                        file: rel_file,
                        params,
                        ssr,
                        static_gen,
                    });
                }
            }
        }
        Ok(())
    }

    /// Scan server/ directory for Rust backend routes (.rs and .psx)
    fn discover_backend_routes(&mut self) -> Result<()> {
        let server_api_dir = self.root.join("server").join("api");
        if !server_api_dir.exists() || !server_api_dir.is_dir() {
            return Ok(());
        }
        self.scan_api_directory(&server_api_dir, "/api")?;
        Ok(())
    }

    /// Recursively scan server/api/ for .rs and .psx route files
    fn scan_api_directory(&mut self, dir: &Path, prefix: &str) -> Result<()> {
        let entries = std::fs::read_dir(dir)
            .with_context(|| format!("Failed to read server/api directory: {}", dir.display()))?;

        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().to_string();

            if path.is_dir() {
                if name.starts_with('_') {
                    continue;
                }
                let route_segment = if name.starts_with('[') && name.ends_with(']') {
                    let param = name[1..name.len() - 1].to_string();
                    format!(":{}", param)
                } else {
                    name.clone()
                };
                let new_prefix = format!("{}/{}", prefix, route_segment);
                self.scan_api_directory(&path, &new_prefix)?;
            } else if path.is_file() {
                let ext = path
                    .extension()
                    .and_then(|e| e.to_str())
                    .unwrap_or("");
                if let Some(backend_ext) = BackendExt::from_ext(ext) {
                    let routes = extract_backend_routes(&path, prefix, backend_ext, &self.root)?;
                    self.backend_routes.extend(routes);
                }
            }
        }
        Ok(())
    }

    /// Scan server/middleware/ for middleware files
    fn discover_middleware(&mut self) -> Result<()> {
        let mw_dir = self.root.join("server").join("middleware");
        if !mw_dir.exists() || !mw_dir.is_dir() {
            return Ok(());
        }
        let entries = std::fs::read_dir(mw_dir)?;
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().to_string();
            if !path.is_file() {
                continue;
            }
            let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
            if let Some(backend_ext) = BackendExt::from_ext(ext) {
                let mw_name = name.split('.').next().unwrap_or("middleware").to_string();
                let rel_file = path
                    .strip_prefix(&self.root)
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .replace('\\', "/");
                self.middleware.push(MiddlewareEntry {
                    file: rel_file,
                    name: mw_name,
                    ext: backend_ext,
                    applies_to: Vec::new(),
                });
            }
        }
        Ok(())
    }

    /// Find server entry point (server/lib.rs or server/lib.psx or server/main.rs)
    fn discover_server_entry(&mut self) -> Result<()> {
        let server_dir = self.root.join("server");
        if !server_dir.exists() || !server_dir.is_dir() {
            return Ok(());
        }
        for candidate in &["lib.rs", "lib.psx", "main.rs", "main.psx"] {
            let path = server_dir.join(candidate);
            if path.exists() {
                self.server_entry = Some(path);
                break;
            }
        }
        Ok(())
    }

    /// Generate a route manifest
    pub fn manifest(&self) -> RouteManifest {
        RouteManifest {
            frontend: self.frontend_routes.clone(),
            backend: self.backend_routes.clone(),
            middleware: self.middleware.clone(),
            server_entry: self.server_entry.as_ref().and_then(|p| {
                p.strip_prefix(&self.root)
                    .ok()
                    .map(|r| r.to_string_lossy().replace('\\', "/"))
            }),
        }
    }

    /// Copy .psx files to .rs in the output directory for cargo build
    pub fn prepare_psx_files(&self, out_dir: &Path) -> Result<Vec<(PathBuf, PathBuf)>> {
        let mut copied = Vec::new();

        for route in &self.backend_routes {
            if route.ext == BackendExt::Psx {
                let src = self.root.join(&route.file);
                let rel = route.file.strip_suffix(".psx").unwrap_or(&route.file);
                let dst = out_dir.join(format!("{}.rs", rel));
                if let Some(parent) = dst.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::copy(&src, &dst)?;
                copied.push((src, dst));
            }
        }

        for mw in &self.middleware {
            if mw.ext == BackendExt::Psx {
                let src = self.root.join(&mw.file);
                let rel = mw.file.strip_suffix(".psx").unwrap_or(&mw.file);
                let dst = out_dir.join(format!("{}.rs", rel));
                if let Some(parent) = dst.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::copy(&src, &dst)?;
                copied.push((src, dst));
            }
        }

        if let Some(ref entry) = self.server_entry {
            let ext = entry.extension().and_then(|e| e.to_str()).unwrap_or("");
            if ext == "psx" {
                let rel = entry
                    .strip_prefix(&self.root)
                    .unwrap_or(entry)
                    .to_string_lossy()
                    .replace('\\', "/");
                let rel_no_ext = rel.strip_suffix(".psx").unwrap_or(&rel);
                let dst = out_dir.join(format!("{}.rs", rel_no_ext));
                if let Some(parent) = dst.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::copy(entry, &dst)?;
                copied.push((entry.clone(), dst));
            }
        }

        Ok(copied)
    }

    /// Write the route manifest to a JSON file
    pub fn write_manifest(&self, out_path: &Path) -> Result<()> {
        let manifest = self.manifest();
        let json = serde_json::to_string_pretty(&manifest)?;
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(out_path, json)?;
        Ok(())
    }
}

/// Extract dynamic params from a route path (e.g., "/blog/:slug" -> ["slug"])
fn extract_params(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|seg| {
            if seg.starts_with(':') {
                Some(seg[1..].to_string())
            } else {
                None
            }
        })
        .collect()
}

/// Detect whether a page supports SSR or is static
fn detect_render_mode(path: &Path) -> (bool, bool) {
    let content = std::fs::read_to_string(path).unwrap_or_default();
    let has_ssr = content.contains("getServerSideProps")
        || content.contains("force-dynamic")
        || content.contains("revalidate = 0");
    let has_ssg = content.contains("getStaticProps")
        || (content.contains("revalidate =") && !content.contains("revalidate = 0"));
    (has_ssr, has_ssg)
}

/// Extract backend routes from a .rs or .psx file by scanning for #[route(...)] macros
fn extract_backend_routes(
    path: &Path,
    prefix: &str,
    ext: BackendExt,
    root: &Path,
) -> Result<Vec<BackendRoute>> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("Failed to read backend route file: {}", path.display()))?;

    let rel_file = path
        .strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/");

    let mut routes = Vec::new();
    let mut pending: Option<(String, String)> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("#[route(") || trimmed.starts_with("#[pledge::route(") {
            if let Some((method, route_path)) = parse_route_attr(trimmed) {
                pending = Some((method, route_path));
            }
        }

        if let Some((method, route_path)) = &pending {
            if let Some(fn_name) = extract_fn_name(trimmed) {
                let params = extract_params(route_path);
                routes.push(BackendRoute {
                    method: method.clone(),
                    path: route_path.clone(),
                    file: rel_file.clone(),
                    handler: fn_name,
                    ext,
                    params,
                });
                pending = None;
            }
        }
    }

    Ok(routes)
}

/// Parse a #[route(...)] attribute line to extract method and path
fn parse_route_attr(line: &str) -> Option<(String, String)> {
    let inner = line
        .strip_prefix("#[route(")
        .or_else(|| line.strip_prefix("#[pledge::route("))
        .and_then(|s| s.strip_suffix(")]"))
        .unwrap_or("");

    // Check for key-value format first: method = "GET", path = "/api/users"
    if inner.contains('=') {
        let mut method = None;
        let mut path = None;
        for part in inner.split(',') {
            let part = part.trim();
            if let Some(val) = part.strip_prefix("method") {
                let val = val.trim();
                if let Some(quoted) = val.strip_prefix("=") {
                    method = Some(quoted.trim().trim_matches('"').to_string());
                }
            } else if let Some(val) = part.strip_prefix("path") {
                let val = val.trim();
                if let Some(quoted) = val.strip_prefix("=") {
                    path = Some(quoted.trim().trim_matches('"').to_string());
                }
            }
        }
        return match (method, path) {
            (Some(m), Some(p)) => Some((m, p)),
            _ => None,
        };
    }

    // Simple format: GET, "/api/users"
    if let Some(comma_pos) = inner.find(',') {
        let method = inner[..comma_pos].trim().trim_matches('"').to_string();
        let path = inner[comma_pos + 1..].trim().trim_matches('"').to_string();
        if !method.is_empty() && !path.is_empty() {
            return Some((method, path));
        }
    }

    None
}

/// Extract function name from a `pub async fn name(` or `pub fn name(` line
fn extract_fn_name(line: &str) -> Option<String> {
    let line = line.trim();
    if let Some(fn_pos) = line.find("fn ") {
        let after_fn = &line[fn_pos + 3..];
        if let Some(paren_pos) = after_fn.find('(') {
            let name = after_fn[..paren_pos].trim();
            if !name.is_empty() {
                return Some(name.to_string());
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_backend_ext_from_str() {
        assert_eq!(BackendExt::from_ext("rs"), Some(BackendExt::Rs));
        assert_eq!(BackendExt::from_ext("psx"), Some(BackendExt::Psx));
        assert_eq!(BackendExt::from_ext("tsx"), None);
    }

    #[test]
    fn test_extract_params() {
        assert_eq!(extract_params("/blog/:slug"), vec!["slug"]);
        assert_eq!(extract_params("/api/users/:id/posts/:post_id"), vec!["id", "post_id"]);
        assert_eq!(extract_params("/"), Vec::<String>::new());
    }

    #[test]
    fn test_parse_route_attr_simple() {
        let result = parse_route_attr(r#"#[route(GET, "/api/users")]"#);
        assert_eq!(result, Some(("GET".to_string(), "/api/users".to_string())));
    }

    #[test]
    fn test_parse_route_attr_qualified() {
        let result = parse_route_attr(r#"#[pledge::route(POST, "/api/auth")]"#);
        assert_eq!(result, Some(("POST".to_string(), "/api/auth".to_string())));
    }

    #[test]
    fn test_parse_route_attr_kv() {
        let result = parse_route_attr(r#"#[route(method = "DELETE", path = "/api/users/:id")]"#);
        assert_eq!(result, Some(("DELETE".to_string(), "/api/users/:id".to_string())));
    }

    #[test]
    fn test_extract_fn_name() {
        assert_eq!(extract_fn_name("pub async fn list_users("), Some("list_users".to_string()));
        assert_eq!(extract_fn_name("pub fn handler("), Some("handler".to_string()));
        assert_eq!(extract_fn_name("fn not_pub("), Some("not_pub".to_string()));
        assert_eq!(extract_fn_name("not a function"), None);
    }
}
