// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
/// Flags indicating which hooks the plugin implements
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HookFlags {
    pub resolve_id: bool,
    pub load: bool,
    pub transform: bool,
    pub transform_index_html: bool,
    pub build_start: bool,
    pub build_end: bool,
    pub generate_bundle: bool,
    pub configure_server: bool,
}
impl ::core::fmt::Debug for HookFlags {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HookFlags")
            .field("resolve-id", &self.resolve_id)
            .field("load", &self.load)
            .field("transform", &self.transform)
            .field("transform-index-html", &self.transform_index_html)
            .field("build-start", &self.build_start)
            .field("build-end", &self.build_end)
            .field("generate-bundle", &self.generate_bundle)
            .field("configure-server", &self.configure_server)
            .finish()
    }
}
/// ─── Types ───────────────────────────────────────────────────────
/// Plugin metadata — returned at instantiation time
#[derive(Clone)]
pub struct PluginMetadata {
    /// Plugin name (required, used in diagnostics and cache keys)
    pub name: _rt::String,
    /// ABI version this plugin targets (must match host's supported version)
    pub version: _rt::String,
    /// Which hooks this plugin implements (host uses this to skip no-op calls)
    pub hooks: HookFlags,
    /// Apply mode: "build", "serve", or "all" (mirrors Vite's `apply` field)
    pub apply: Option<_rt::String>,
    /// Plugin ordering: "pre" runs before built-in transform, "post" runs after.
    /// Default (none) is "post". Mirrors Vite's `enforce` field.
    /// Added in v0.1.1 (additive, backward-compatible).
    pub enforce: Option<_rt::String>,
}
impl ::core::fmt::Debug for PluginMetadata {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PluginMetadata")
            .field("name", &self.name)
            .field("version", &self.version)
            .field("hooks", &self.hooks)
            .field("apply", &self.apply)
            .field("enforce", &self.enforce)
            .finish()
    }
}
/// ─── resolveId hook ──────────────────────────────────────────────
///
/// Called when an import specifier needs to be resolved to a module ID.
/// Sequential: plugins are called in order; first non-null result wins.
/// Mirrors Vite/Rollup `resolveId(source, importer, options)`.
#[derive(Clone)]
pub struct ResolveIdInput {
    /// The import specifier to resolve (e.g., "./foo", "react", "virtual:my-mod")
    pub source: _rt::String,
    /// The file that contains the import (None for entry points)
    pub importer: Option<_rt::String>,
    /// Whether this is an entry point import
    pub is_entry: bool,
    /// Import kind: "import", "dynamic-import", "require", "import.meta.resolve"
    pub kind: Option<_rt::String>,
}
impl ::core::fmt::Debug for ResolveIdInput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ResolveIdInput")
            .field("source", &self.source)
            .field("importer", &self.importer)
            .field("is-entry", &self.is_entry)
            .field("kind", &self.kind)
            .finish()
    }
}
#[derive(Clone)]
pub struct ResolveIdOutput {
    /// The resolved module ID (file path or virtual module ID)
    pub id: _rt::String,
    /// Whether this module should be treated as external (not bundled)
    pub external: bool,
    /// Cache key: hash of all inputs that affect this result
    /// The host uses this to cache the resolve result as a task graph node
    pub cache_key: _rt::String,
}
impl ::core::fmt::Debug for ResolveIdOutput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ResolveIdOutput")
            .field("id", &self.id)
            .field("external", &self.external)
            .field("cache-key", &self.cache_key)
            .finish()
    }
}
/// ─── load hook ───────────────────────────────────────────────────
///
/// Called to load the source code for a module ID.
/// Sequential: first non-null result wins.
/// Mirrors Vite/Rollup `load(id)`.
#[derive(Clone)]
pub struct LoadInput {
    /// The module ID to load (from resolveId or file path)
    pub id: _rt::String,
}
impl ::core::fmt::Debug for LoadInput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("LoadInput").field("id", &self.id).finish()
    }
}
#[derive(Clone)]
pub struct LoadOutput {
    /// The loaded source code
    pub code: _rt::String,
    /// Optional source map (JSON string)
    pub source_map: Option<_rt::String>,
    /// Cache key: hash of all inputs that affect this result
    pub cache_key: _rt::String,
}
impl ::core::fmt::Debug for LoadOutput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("LoadOutput")
            .field("code", &self.code)
            .field("source-map", &self.source_map)
            .field("cache-key", &self.cache_key)
            .finish()
    }
}
/// ─── transform hook ──────────────────────────────────────────────
///
/// Called to transform module source code.
/// Sequential chain: each plugin sees the output of the previous plugin.
/// Mirrors Vite/Rollup `transform(code, id)`.
///
/// The host may provide the pre-parsed AST via `ast-json` if the plugin
/// declares `needs-ast: true` in its metadata (Phase 0/2 extension).
#[derive(Clone)]
pub struct TransformInput {
    /// The source code to transform
    pub code: _rt::String,
    /// The module ID (file path or virtual ID)
    pub id: _rt::String,
    /// Optional: pre-parsed AST as JSON (ESTree format)
    /// Present only if the plugin declared `needs-ast: true` AND the host
    /// supports AST serialization. Plugins must handle `none` gracefully.
    pub ast_json: Option<_rt::String>,
}
impl ::core::fmt::Debug for TransformInput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("TransformInput")
            .field("code", &self.code)
            .field("id", &self.id)
            .field("ast-json", &self.ast_json)
            .finish()
    }
}
#[derive(Clone)]
pub struct TransformOutput {
    /// The transformed source code
    pub code: _rt::String,
    /// Optional source map (JSON string)
    pub source_map: Option<_rt::String>,
    /// Cache key: hash of all inputs that affect this result
    /// The host uses this to cache the transform result as a task graph node
    pub cache_key: _rt::String,
}
impl ::core::fmt::Debug for TransformOutput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("TransformOutput")
            .field("code", &self.code)
            .field("source-map", &self.source_map)
            .field("cache-key", &self.cache_key)
            .finish()
    }
}
/// ─── transformIndexHtml hook ─────────────────────────────────────
///
/// Called to transform the index.html file.
/// Sequential: each plugin sees the output of the previous plugin.
/// Mirrors Vite `transformIndexHtml(html)`.
#[derive(Clone)]
pub struct HtmlInput {
    /// The HTML content to transform
    pub html: _rt::String,
    /// The file path of the HTML file
    pub path: _rt::String,
}
impl ::core::fmt::Debug for HtmlInput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HtmlInput")
            .field("html", &self.html)
            .field("path", &self.path)
            .finish()
    }
}
#[derive(Clone)]
pub struct HtmlTag {
    /// Tag name (e.g., "script", "link", "meta")
    pub tag: _rt::String,
    /// Attributes as key-value pairs
    pub attrs: _rt::Vec<(_rt::String, _rt::String)>,
    /// Children content (for tags with content)
    pub children: Option<_rt::String>,
    /// Where to inject: "head", "body-start", "body-end", "head-prepend"
    pub inject_to: Option<_rt::String>,
}
impl ::core::fmt::Debug for HtmlTag {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HtmlTag")
            .field("tag", &self.tag)
            .field("attrs", &self.attrs)
            .field("children", &self.children)
            .field("inject-to", &self.inject_to)
            .finish()
    }
}
#[derive(Clone)]
pub struct HtmlOutput {
    /// The transformed HTML content
    pub html: _rt::String,
    /// Tags to inject into the HTML (alternative to modifying html directly)
    pub tags: _rt::Vec<HtmlTag>,
    /// Cache key
    pub cache_key: _rt::String,
}
impl ::core::fmt::Debug for HtmlOutput {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HtmlOutput")
            .field("html", &self.html)
            .field("tags", &self.tags)
            .field("cache-key", &self.cache_key)
            .finish()
    }
}
/// ─── configureServer hook (dev mode only) ────────────────────────
///
/// Called to register dev server middleware.
/// Mirrors Vite `configureServer(server)`.
#[derive(Clone)]
pub struct ServerMiddleware {
    /// The plugin name (for diagnostics)
    pub plugin_name: _rt::String,
    /// Middleware source code (JS function to be evaluated)
    /// For WASM plugins, this is a WAT/WASM module that exports a handler
    pub source: _rt::String,
}
impl ::core::fmt::Debug for ServerMiddleware {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ServerMiddleware")
            .field("plugin-name", &self.plugin_name)
            .field("source", &self.source)
            .finish()
    }
}
#[allow(unused_unsafe, clippy::all)]
/// ─── Host imports (Item 6) ──────────────────────────────────────
///
/// These are functions the host (PledgePack) provides to plugins.
/// Plugins can call these to access host functionality.
/// Added in v0.1.1 (additive, backward-compatible).
/// Get the PledgePack config as JSON string.
/// Plugins can use this to read user configuration (e.g., plugin options).
pub fn get_config() -> _rt::String {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "get-config"]
            fn wit_import1(_: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import1(_: *mut u8) {
            unreachable!()
        }
        unsafe { wit_import1(ptr0) };
        let l2 = *ptr0.add(0).cast::<*mut u8>();
        let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len4 = l3;
        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
        let result5 = _rt::string_lift(bytes4);
        result5
    }
}
#[allow(unused_unsafe, clippy::all)]
/// Emit a file to the output directory.
/// Returns true if the file was written successfully.
/// Plugins can use this to generate additional assets (e.g., CSS files,
/// source maps, JSON manifests).
pub fn emit_file(name: &str, content: &str) -> bool {
    unsafe {
        let vec0 = name;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = content;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "emit-file"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32;
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import2(
            _: *mut u8,
            _: usize,
            _: *mut u8,
            _: usize,
        ) -> i32 {
            unreachable!()
        }
        let ret = unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
        _rt::bool_lift(ret as u8)
    }
}
#[allow(unused_unsafe, clippy::all)]
/// Resolve a module specifier relative to the host's module graph.
/// This enables plugins to resolve imports recursively (e.g., for
/// virtual modules that depend on other virtual modules).
/// Returns the resolved ID, or none if the specifier could not be resolved.
pub fn resolve_import(specifier: &str, importer: &str) -> Option<_rt::String> {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
        );
        let vec0 = specifier;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = importer;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "resolve-import"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import3(
            _: *mut u8,
            _: usize,
            _: *mut u8,
            _: usize,
            _: *mut u8,
        ) {
            unreachable!()
        }
        unsafe { wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2) };
        let l4 = i32::from(*ptr2.add(0).cast::<u8>());
        let result8 = match l4 {
            0 => None,
            1 => {
                let e = {
                    let l5 = *ptr2
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l6 = *ptr2
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len7 = l6;
                    let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                    _rt::string_lift(bytes7)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        };
        result8
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_plugin_metadata_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::plugin_metadata();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let PluginMetadata {
        name: name2,
        version: version2,
        hooks: hooks2,
        apply: apply2,
        enforce: enforce2,
    } = result0;
    let vec3 = (name2.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    let vec4 = (version2.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
        .cast_mut();
    let HookFlags {
        resolve_id: resolve_id5,
        load: load5,
        transform: transform5,
        transform_index_html: transform_index_html5,
        build_start: build_start5,
        build_end: build_end5,
        generate_bundle: generate_bundle5,
        configure_server: configure_server5,
    } = hooks2;
    *ptr1.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match resolve_id5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(1 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match load5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(2 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match transform5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(3 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match transform_index_html5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(4 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match build_start5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(5 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match build_end5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(6 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match generate_bundle5 {
        true => 1,
        false => 0,
    }) as u8;
    *ptr1.add(7 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match configure_server5 {
        true => 1,
        false => 0,
    }) as u8;
    match apply2 {
        Some(e) => {
            *ptr1.add(8 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                as u8;
            let vec6 = (e.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr1.add(8 + 6 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *ptr1.add(8 + 5 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
                .cast_mut();
        }
        None => {
            *ptr1.add(8 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                as u8;
        }
    };
    match enforce2 {
        Some(e) => {
            *ptr1.add(8 + 7 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                as u8;
            let vec7 = (e.into_bytes()).into_boxed_slice();
            let ptr7 = vec7.as_ptr().cast::<u8>();
            let len7 = vec7.len();
            ::core::mem::forget(vec7);
            *ptr1.add(8 + 9 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
            *ptr1.add(8 + 8 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7
                .cast_mut();
        }
        None => {
            *ptr1.add(8 + 7 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                as u8;
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_plugin_metadata<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
    let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l3 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l2, l3, 1);
    let l4 = i32::from(
        *arg0.add(8 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    match l4 {
        0 => {}
        _ => {
            let l5 = *arg0
                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l6 = *arg0
                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
        }
    }
    let l7 = i32::from(
        *arg0.add(8 + 7 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    match l7 {
        0 => {}
        _ => {
            let l8 = *arg0
                .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l9 = *arg0
                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l8, l9, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_resolve_id_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: *mut u8,
    arg4: usize,
    arg5: i32,
    arg6: i32,
    arg7: *mut u8,
    arg8: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result3 = T::resolve_id(ResolveIdInput {
        source: _rt::string_lift(bytes0),
        importer: match arg2 {
            0 => None,
            1 => {
                let e = {
                    let len1 = arg4;
                    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                    _rt::string_lift(bytes1)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
        is_entry: _rt::bool_lift(arg5 as u8),
        kind: match arg6 {
            0 => None,
            1 => {
                let e = {
                    let len2 = arg8;
                    let bytes2 = _rt::Vec::from_raw_parts(arg7.cast(), len2, len2);
                    _rt::string_lift(bytes2)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    });
    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result3 {
        Some(e) => {
            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
            let ResolveIdOutput {
                id: id5,
                external: external5,
                cache_key: cache_key5,
            } = e;
            let vec6 = (id5.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr4.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
                .cast_mut();
            *ptr4.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match external5 {
                true => 1,
                false => 0,
            }) as u8;
            let vec7 = (cache_key5.into_bytes()).into_boxed_slice();
            let ptr7 = vec7.as_ptr().cast::<u8>();
            let len7 = vec7.len();
            ::core::mem::forget(vec7);
            *ptr4.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
            *ptr4.add(4 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7
                .cast_mut();
        }
        None => {
            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr4
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_resolve_id<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = *arg0
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l4 = *arg0.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_load_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::load(LoadInput {
        id: _rt::string_lift(bytes0),
    });
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Some(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let LoadOutput {
                code: code3,
                source_map: source_map3,
                cache_key: cache_key3,
            } = e;
            let vec4 = (code3.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
            match source_map3 {
                Some(e) => {
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                    let vec5 = (e.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr2.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr2
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                }
                None => {
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                }
            };
            let vec6 = (cache_key3.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr2.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *ptr2.add(6 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
                .cast_mut();
        }
        None => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_load<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = i32::from(
                *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l3 {
                0 => {}
                _ => {
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                }
            }
            let l6 = *arg0
                .add(6 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l7 = *arg0.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l6, l7, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_transform_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
    arg4: i32,
    arg5: *mut u8,
    arg6: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let result3 = T::transform(TransformInput {
        code: _rt::string_lift(bytes0),
        id: _rt::string_lift(bytes1),
        ast_json: match arg4 {
            0 => None,
            1 => {
                let e = {
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    _rt::string_lift(bytes2)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    });
    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result3 {
        Some(e) => {
            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
            let TransformOutput {
                code: code5,
                source_map: source_map5,
                cache_key: cache_key5,
            } = e;
            let vec6 = (code5.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr4.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
                .cast_mut();
            match source_map5 {
                Some(e) => {
                    *ptr4.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                    let vec7 = (e.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *ptr4.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr4
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                }
                None => {
                    *ptr4.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                }
            };
            let vec8 = (cache_key5.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *ptr4.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *ptr4.add(6 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8
                .cast_mut();
        }
        None => {
            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr4
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_transform<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = i32::from(
                *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l3 {
                0 => {}
                _ => {
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                }
            }
            let l6 = *arg0
                .add(6 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l7 = *arg0.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l6, l7, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_transform_index_html_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let result2 = T::transform_index_html(HtmlInput {
        html: _rt::string_lift(bytes0),
        path: _rt::string_lift(bytes1),
    });
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result2 {
        Some(e) => {
            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
            let HtmlOutput { html: html4, tags: tags4, cache_key: cache_key4 } = e;
            let vec5 = (html4.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
            let vec14 = tags4;
            let len14 = vec14.len();
            let layout14 = _rt::alloc::Layout::from_size_align_unchecked(
                vec14.len() * (10 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result14 = if layout14.size() != 0 {
                let ptr = _rt::alloc::alloc(layout14).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout14);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec14.into_iter().enumerate() {
                let base = result14.add(i * (10 * ::core::mem::size_of::<*const u8>()));
                {
                    let HtmlTag {
                        tag: tag6,
                        attrs: attrs6,
                        children: children6,
                        inject_to: inject_to6,
                    } = e;
                    let vec7 = (tag6.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *base.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                    let vec11 = attrs6;
                    let len11 = vec11.len();
                    let layout11 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec11.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result11 = if layout11.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout11).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout11);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec11.into_iter().enumerate() {
                        let base = result11
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t8_0, t8_1) = e;
                            let vec9 = (t8_0.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *base.add(0).cast::<*mut u8>() = ptr9.cast_mut();
                            let vec10 = (t8_1.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                        }
                    }
                    *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
                    *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result11;
                    match children6 {
                        Some(e) => {
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec12 = (e.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                        None => {
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match inject_to6 {
                        Some(e) => {
                            *base
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec13 = (e.into_bytes()).into_boxed_slice();
                            let ptr13 = vec13.as_ptr().cast::<u8>();
                            let len13 = vec13.len();
                            ::core::mem::forget(vec13);
                            *base
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len13;
                            *base
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr13.cast_mut();
                        }
                        None => {
                            *base
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                }
            }
            *ptr3.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
            *ptr3.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result14;
            let vec15 = (cache_key4.into_bytes()).into_boxed_slice();
            let ptr15 = vec15.as_ptr().cast::<u8>();
            let len15 = vec15.len();
            ::core::mem::forget(vec15);
            *ptr3.add(6 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
            *ptr3.add(5 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr15
                .cast_mut();
        }
        None => {
            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_transform_index_html<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l4 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base20 = l3;
            let len20 = l4;
            for i in 0..len20 {
                let base = base20.add(i * (10 * ::core::mem::size_of::<*const u8>()));
                {
                    let l5 = *base.add(0).cast::<*mut u8>();
                    let l6 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l5, l6, 1);
                    let l7 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l8 = *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base13 = l7;
                    let len13 = l8;
                    for i in 0..len13 {
                        let base = base13
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l9 = *base.add(0).cast::<*mut u8>();
                            let l10 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l9, l10, 1);
                            let l11 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l12 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l11, l12, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base13,
                        len13 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l14 = i32::from(
                        *base.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l14 {
                        0 => {}
                        _ => {
                            let l15 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l15, l16, 1);
                        }
                    }
                    let l17 = i32::from(
                        *base.add(7 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l17 {
                        0 => {}
                        _ => {
                            let l18 = *base
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l19 = *base
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l18, l19, 1);
                        }
                    }
                }
            }
            _rt::cabi_dealloc(
                base20,
                len20 * (10 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let l21 = *arg0
                .add(5 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l22 = *arg0.add(6 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l21, l22, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_build_start_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::build_start();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_build_end_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::build_end();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_generate_bundle_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::generate_bundle();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_configure_server_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::configure_server();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Some(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let ServerMiddleware { plugin_name: plugin_name2, source: source2 } = e;
            let vec3 = (plugin_name2.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3
                .cast_mut();
            let vec4 = (source2.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr1.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
        }
        None => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_configure_server<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l4 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
pub trait Guest {
    /// The plugin declares its metadata at instantiation time
    fn plugin_metadata() -> PluginMetadata;
    /// Module pipeline hooks (sequential, first-result-wins for resolve/load,
    /// chain for transform)
    fn resolve_id(input: ResolveIdInput) -> Option<ResolveIdOutput>;
    fn load(input: LoadInput) -> Option<LoadOutput>;
    fn transform(input: TransformInput) -> Option<TransformOutput>;
    /// HTML transform hook (sequential)
    fn transform_index_html(input: HtmlInput) -> Option<HtmlOutput>;
    /// Lifecycle hooks (parallel — all plugins called, order not guaranteed)
    fn build_start() -> ();
    fn build_end() -> ();
    fn generate_bundle() -> ();
    /// Dev server hook (dev mode only)
    fn configure_server() -> Option<ServerMiddleware>;
}
#[doc(hidden)]
macro_rules! __export_world_pledgepack_plugin_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "plugin-metadata")] unsafe extern "C" fn
        export_plugin_metadata() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_plugin_metadata_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_plugin-metadata")] unsafe extern "C" fn
        _post_return_plugin_metadata(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_plugin_metadata::<$ty > (arg0) } } #[unsafe (export_name =
        "resolve-id")] unsafe extern "C" fn export_resolve_id(arg0 : * mut u8, arg1 :
        usize, arg2 : i32, arg3 : * mut u8, arg4 : usize, arg5 : i32, arg6 : i32, arg7 :
        * mut u8, arg8 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_resolve_id_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7,
        arg8) } } #[unsafe (export_name = "cabi_post_resolve-id")] unsafe extern "C" fn
        _post_return_resolve_id(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_resolve_id::<$ty > (arg0) } } #[unsafe (export_name = "load")]
        unsafe extern "C" fn export_load(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_load_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_load")] unsafe extern "C" fn _post_return_load(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_load::<$ty > (arg0) } }
        #[unsafe (export_name = "transform")] unsafe extern "C" fn export_transform(arg0
        : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : i32, arg5 : * mut
        u8, arg6 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_transform_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5, arg6) } }
        #[unsafe (export_name = "cabi_post_transform")] unsafe extern "C" fn
        _post_return_transform(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_transform::<$ty > (arg0) } } #[unsafe (export_name =
        "transform-index-html")] unsafe extern "C" fn export_transform_index_html(arg0 :
        * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_transform_index_html_cabi::<$ty > (arg0, arg1, arg2,
        arg3) } } #[unsafe (export_name = "cabi_post_transform-index-html")] unsafe
        extern "C" fn _post_return_transform_index_html(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_transform_index_html::<$ty > (arg0) } }
        #[unsafe (export_name = "build-start")] unsafe extern "C" fn export_build_start()
        { unsafe { $($path_to_types)*:: _export_build_start_cabi::<$ty > () } } #[unsafe
        (export_name = "build-end")] unsafe extern "C" fn export_build_end() { unsafe {
        $($path_to_types)*:: _export_build_end_cabi::<$ty > () } } #[unsafe (export_name
        = "generate-bundle")] unsafe extern "C" fn export_generate_bundle() { unsafe {
        $($path_to_types)*:: _export_generate_bundle_cabi::<$ty > () } } #[unsafe
        (export_name = "configure-server")] unsafe extern "C" fn
        export_configure_server() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_configure_server_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_configure-server")] unsafe extern "C" fn
        _post_return_configure_server(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_configure_server::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_pledgepack_plugin_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea(
    [::core::mem::MaybeUninit<u8>; 8 + 10 * ::core::mem::size_of::<*const u8>()],
);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 8 + 10 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_pledgepack_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_pledgepack_plugin_cabi!($ty
        with_types_in $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_pledgepack_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pledgepack:plugin@0.1.1:pledgepack-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1175] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8f\x08\x01A\x02\x01\
A7\x01r\x08\x0aresolve-id\x7f\x04load\x7f\x09transform\x7f\x14transform-index-ht\
ml\x7f\x0bbuild-start\x7f\x09build-end\x7f\x0fgenerate-bundle\x7f\x10configure-s\
erver\x7f\x03\0\x0ahook-flags\x03\0\0\x01ks\x01r\x05\x04names\x07versions\x05hoo\
ks\x01\x05apply\x02\x07enforce\x02\x03\0\x0fplugin-metadata\x03\0\x03\x01r\x04\x06\
sources\x08importer\x02\x08is-entry\x7f\x04kind\x02\x03\0\x10resolve-id-input\x03\
\0\x05\x01r\x03\x02ids\x08external\x7f\x09cache-keys\x03\0\x11resolve-id-output\x03\
\0\x07\x01r\x01\x02ids\x03\0\x0aload-input\x03\0\x09\x01r\x03\x04codes\x0asource\
-map\x02\x09cache-keys\x03\0\x0bload-output\x03\0\x0b\x01r\x03\x04codes\x02ids\x08\
ast-json\x02\x03\0\x0ftransform-input\x03\0\x0d\x01r\x03\x04codes\x0asource-map\x02\
\x09cache-keys\x03\0\x10transform-output\x03\0\x0f\x01r\x02\x04htmls\x04paths\x03\
\0\x0ahtml-input\x03\0\x11\x01o\x02ss\x01p\x13\x01r\x04\x03tags\x05attrs\x14\x08\
children\x02\x09inject-to\x02\x03\0\x08html-tag\x03\0\x15\x01p\x16\x01r\x03\x04h\
tmls\x04tags\x17\x09cache-keys\x03\0\x0bhtml-output\x03\0\x18\x01r\x02\x0bplugin\
-names\x06sources\x03\0\x11server-middleware\x03\0\x1a\x01@\0\0s\x03\0\x0aget-co\
nfig\x01\x1c\x01@\x02\x04names\x07contents\0\x7f\x03\0\x09emit-file\x01\x1d\x01@\
\x02\x09specifiers\x08importers\0\x02\x03\0\x0eresolve-import\x01\x1e\x01@\0\0\x04\
\x04\0\x0fplugin-metadata\x01\x1f\x01k\x08\x01@\x01\x05input\x06\0\x20\x04\0\x0a\
resolve-id\x01!\x01k\x0c\x01@\x01\x05input\x0a\0\"\x04\0\x04load\x01#\x01k\x10\x01\
@\x01\x05input\x0e\0$\x04\0\x09transform\x01%\x01k\x19\x01@\x01\x05input\x12\0&\x04\
\0\x14transform-index-html\x01'\x01@\0\x01\0\x04\0\x0bbuild-start\x01(\x04\0\x09\
build-end\x01(\x04\0\x0fgenerate-bundle\x01(\x01k\x1b\x01@\0\0)\x04\0\x10configu\
re-server\x01*\x04\0)pledgepack:plugin/pledgepack-plugin@0.1.1\x04\0\x0b\x17\x01\
\0\x11pledgepack-plugin\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-c\
omponent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
