// Advanced features — Roadmap v2 items 110, 115-120

use anyhow::Result;
use std::collections::HashMap;
use std::path::Path;

// ─── 110: Web Components compilation ──────────────────────────────────

pub fn is_web_component_file(file_path: &str) -> bool {
    file_path.ends_with(".wc.tsx") || file_path.ends_with(".wc.jsx")
}

pub fn compile_web_component(source: &str, file_path: &str) -> Result<String> {
    let component_name = extract_component_name(source, file_path);
    let tag_name = to_kebab_case(&component_name);
    let css = extract_scoped_css(source);
    let render_body = extract_render_body(source);

    let style_injection = if css.is_empty() {
        String::new()
    } else {
        format!(
            "      const style = document.createElement('style');\n      style.textContent = `{}`;\n      shadow.appendChild(style);",
            css
        )
    };

    Ok(format!(
"// Generated by Pledgepack — Web Component from {file_path}
class {class_name} extends HTMLElement {{
  constructor() {{
    super();
    const shadow = this.attachShadow({{ mode: 'open' }});
{style_injection}
    const container = document.createElement('div');
    container.innerHTML = `{render}`;
    shadow.appendChild(container);
  }}
  connectedCallback() {{}}
  disconnectedCallback() {{}}
  static get observedAttributes() {{ return []; }}
}}
customElements.define('{tag}', {class_name});
export {{ {class_name} }};
",
        file_path = file_path,
        class_name = component_name,
        style_injection = style_injection,
        render = render_body,
        tag = tag_name,
    ))
}

fn extract_component_name(source: &str, file_path: &str) -> String {
    for line in source.lines() {
        let t = line.trim();
        if let Some(r) = t.strip_prefix("export function ") {
            if let Some(name) = r.split(|c: char| !c.is_alphanumeric() && c != '_').next() {
                if !name.is_empty() { return name.to_string(); }
            }
        }
        if let Some(r) = t.strip_prefix("export const ") {
            if let Some(name) = r.split(|c: char| !c.is_alphanumeric() && c != '_').next() {
                if !name.is_empty() { return name.to_string(); }
            }
        }
    }
    Path::new(file_path).file_stem().and_then(|s| s.to_str()).map(|s| {
        let mut r = String::new();
        let mut cap = true;
        for ch in s.chars() {
            if ch == '-' || ch == '_' { cap = true; }
            else if cap { r.push(ch.to_ascii_uppercase()); cap = false; }
            else { r.push(ch); }
        }
        r
    }).unwrap_or_else(|| "MyElement".to_string())
}

fn to_kebab_case(name: &str) -> String {
    let mut r = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 { r.push('-'); }
            r.push(ch.to_ascii_lowercase());
        } else { r.push(ch); }
    }
    r
}

fn extract_scoped_css(source: &str) -> String {
    let mut rules = Vec::new();
    for line in source.lines() {
        let t = line.trim();
        if let Some(pos) = t.find("className=\"") {
            let after = &t[pos + 11..];
            if let Some(end) = after.find('"') {
                for cn in after[..end].split_whitespace() {
                    rules.push(format!(".{} {{ }}", cn));
                }
            }
        }
    }
    rules.join("\n")
}

fn extract_render_body(source: &str) -> String {
    if let Some(rp) = source.find("return ") {
        let after = &source[rp + 7..];
        if let Some(xs) = after.find('<') {
            let jsx = &after[xs..];
            if let Some(semi) = jsx.find(';') { return jsx[..semi].trim().to_string(); }
            if let Some(brace) = jsx.rfind('}') { return jsx[..brace].trim().to_string(); }
            return jsx.trim().to_string();
        }
    }
    "<div></div>".to_string()
}

// ─── 115: Module federation ───────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct FederationConfig {
    pub name: String,
    pub remotes: HashMap<String, String>,
    pub exposes: HashMap<String, String>,
    pub shared: Vec<SharedModule>,
}

#[derive(Debug, Clone)]
pub struct SharedModule {
    pub name: String,
    pub required_version: Option<String>,
    pub eager: bool,
    pub singleton: bool,
}

pub fn generate_federation_host_bootstrap(cfg: &FederationConfig) -> String {
    let remotes: Vec<String> = cfg.remotes.iter()
        .map(|(n, u)| format!("  \"{}\": () => import(\"{}\").then(m => m.default || m)", n, u))
        .collect();
    let shared: Vec<String> = cfg.shared.iter()
        .map(|s| format!("  \"{}\": {{ requiredVersion: \"{}\"{}{} }}",
            s.name, s.required_version.as_deref().unwrap_or("*"),
            if s.singleton { ", singleton: true" } else { "" },
            if s.eager { ", eager: true" } else { "" }))
        .collect();
    format!(
"// Generated by Pledgepack — Module Federation host
const __pledge_federation__ = {{
  remotes: {{\n{}\n  }},
  shared: {{\n{}\n  }},
  init(name) {{ return this.remotes[name](); }},
  loadRemote(name, mod) {{ return this.init(name).then(c => c.get(mod).then(f => f())); }}
}};
window.__pledge_federation__ = __pledge_federation__;\n",
        remotes.join(",\n"), shared.join(",\n"))
}

pub fn generate_federation_remote_entry(cfg: &FederationConfig) -> String {
    let exposes: Vec<String> = cfg.exposes.iter()
        .map(|(e, l)| format!("  \"{}\": () => import(\"{}\").then(m => m.default || m)", e, l))
        .collect();
    let shared: Vec<String> = cfg.shared.iter()
        .map(|s| format!("  \"{}\": () => import(\"{}\").then(m => m.default || m)", s.name, s.name))
        .collect();
    format!(
"// Generated by Pledgepack — Module Federation remote entry
const __pledge_remote__ = {{
  exposes: {{\n{}\n  }},
  shared: {{\n{}\n  }},
  get(mod) {{ if (!this.exposes[mod]) return Promise.reject(new Error(`No exposed module: ${{mod}}`)); return this.exposes[mod](); }},
  init(scope) {{ return Promise.resolve(scope); }}
}};
export default __pledge_remote__;\n",
        exposes.join(",\n"), shared.join(",\n"))
}

pub fn parse_federation_config(raw: &serde_json::Value) -> Option<FederationConfig> {
    let name = raw.get("name")?.as_str()?.to_string();
    let mut remotes = HashMap::new();
    if let Some(r) = raw.get("remotes").and_then(|v| v.as_object()) {
        for (k, v) in r { if let Some(u) = v.as_str() { remotes.insert(k.clone(), u.to_string()); } }
    }
    let mut exposes = HashMap::new();
    if let Some(e) = raw.get("exposes").and_then(|v| v.as_object()) {
        for (k, v) in e { if let Some(p) = v.as_str() { exposes.insert(k.clone(), p.to_string()); } }
    }
    let mut shared = Vec::new();
    if let Some(s) = raw.get("shared").and_then(|v| v.as_array()) {
        for item in s {
            if let Some(n) = item.get("name").and_then(|n| n.as_str()) {
                shared.push(SharedModule {
                    name: n.to_string(),
                    required_version: item.get("requiredVersion").and_then(|v| v.as_str()).map(String::from),
                    eager: item.get("eager").and_then(|v| v.as_bool()).unwrap_or(false),
                    singleton: item.get("singleton").and_then(|v| v.as_bool()).unwrap_or(false),
                });
            } else if let Some(n) = item.as_str() {
                shared.push(SharedModule { name: n.to_string(), required_version: None, eager: false, singleton: false });
            }
        }
    }
    Some(FederationConfig { name, remotes, exposes, shared })
}

// ─── 116: GraphQL code generation ─────────────────────────────────────

#[derive(Debug, Clone)]
pub struct GraphqlCodegenConfig {
    pub schema: String,
    pub output: String,
    pub typescript: bool,
    pub react_hooks: bool,
}

pub fn generate_graphql_types(schema_source: &str, cfg: &GraphqlCodegenConfig) -> Result<String> {
    let types = parse_graphql_schema(schema_source);
    let mut out = String::from("// Generated by Pledgepack — GraphQL codegen\n\n");
    for (type_name, fields) in &types {
        out.push_str(&format!("export interface {} {{\n", type_name));
        for (fname, ftype) in fields {
            out.push_str(&format!("  {}: {};\n", fname, gql_type_to_ts(ftype)));
        }
        out.push_str("}\n\n");
    }
    if cfg.react_hooks {
        out.push_str("// React hooks\n");
        for (tn, fields) in &types {
            if tn == "Query" {
                for (fn_, ft) in fields {
                    out.push_str(&format!(
                        "export function use{}(): {{ data: {} | null; loading: boolean; error: Error | null }};\n",
                        to_pascal(fn_), gql_type_to_ts(ft)));
                }
            }
        }
    }
    Ok(out)
}

fn parse_graphql_schema(src: &str) -> Vec<(String, Vec<(String, String)>)> {
    let mut types = Vec::new();
    let mut cur_type: Option<String> = None;
    let mut cur_fields: Vec<(String, String)> = Vec::new();
    for line in src.lines() {
        let t = line.trim();
        if t.starts_with('#') || t.is_empty() { continue; }
        if let Some(r) = t.strip_prefix("type ").and_then(|s| s.strip_suffix(" {"))
            .or_else(|| t.strip_prefix("interface ").and_then(|s| s.strip_suffix(" {")))
        {
            if let Some(n) = cur_type.take() { types.push((n, std::mem::take(&mut cur_fields))); }
            cur_type = Some(r.trim().to_string());
            continue;
        }
        if t == "}" {
            if let Some(n) = cur_type.take() { types.push((n, std::mem::take(&mut cur_fields))); }
            continue;
        }
        if cur_type.is_some() {
            if let Some(cp) = t.find(':') {
                let fn_ = t[..cp].trim().to_string();
                let ft = t[cp + 1..].trim().trim_end_matches(',').to_string();
                if !fn_.is_empty() && !ft.is_empty() { cur_fields.push((fn_, ft)); }
            }
        }
    }
    if let Some(n) = cur_type { types.push((n, cur_fields)); }
    types
}

fn gql_type_to_ts(gt: &str) -> String {
    let non_null = gt.ends_with('!');
    let base = gt.trim_end_matches('!').trim_end_matches(']');
    let inner = base.trim_start_matches('[').trim_end_matches('!').trim();
    let ts = match inner {
        "String" | "ID" => "string",
        "Int" | "Float" => "number",
        "Boolean" => "boolean",
        "JSON" | "JSONObject" => "Record<string, unknown>",
        _ => inner,
    };
    let array = gt.contains('[') && gt.contains(']');
    let mut r = if array { format!("{}[]", ts) } else { ts.to_string() };
    if !non_null { r.push_str(" | null"); }
    r
}

fn to_pascal(s: &str) -> String {
    let mut r = String::new();
    let mut cap = true;
    for ch in s.chars() {
        if ch == '_' || ch == '-' { cap = true; continue; }
        if cap { r.push(ch.to_ascii_uppercase()); cap = false; } else { r.push(ch); }
    }
    r
}

// ─── 117: Environment-specific builds ─────────────────────────────────

pub fn load_env_file(root: &Path, env_name: &str) -> HashMap<String, String> {
    let env_path = root.join(format!(".env.{}", env_name));
    let mut vars = HashMap::new();
    if let Ok(content) = std::fs::read_to_string(&env_path) {
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') { continue; }
            if let Some(eq) = line.find('=') {
                let key = line[..eq].trim().to_string();
                let val = line[eq + 1..].trim().trim_matches('"').trim_matches('\'').to_string();
                vars.insert(key, val);
            }
        }
    }
    vars
}

pub fn resolve_node_env(env_vars: &HashMap<String, String>, is_production: bool) -> String {
    if let Some(node_env) = env_vars.get("NODE_ENV") {
        return node_env.clone();
    }
    if is_production { "production".to_string() } else { "development".to_string() }
}

// ─── 118: Post-build optimization hooks ───────────────────────────────

#[derive(Debug, Clone)]
pub struct PostBuildContext {
    pub out_dir: std::path::PathBuf,
    pub html_path: Option<std::path::PathBuf>,
    pub chunks: Vec<String>,
    pub assets: Vec<String>,
}

#[derive(Debug, Clone, Default)]
pub struct PostBuildResult {
    pub html_modified: bool,
    pub sitemap_generated: bool,
    pub meta_tags_added: Vec<String>,
    pub warnings: Vec<String>,
}

pub fn run_post_build_hooks(ctx: &PostBuildContext) -> Result<PostBuildResult> {
    let mut result = PostBuildResult::default();
    if let Some(ref html_path) = ctx.html_path {
        if html_path.exists() {
            let sitemap = generate_sitemap(&ctx.out_dir, &ctx.chunks);
            std::fs::write(ctx.out_dir.join("sitemap.xml"), &sitemap)?;
            result.sitemap_generated = true;
            let html = std::fs::read_to_string(html_path)?;
            let (modified_html, added_tags) = inject_meta_tags(&html);
            if !added_tags.is_empty() {
                std::fs::write(html_path, &modified_html)?;
                result.html_modified = true;
                result.meta_tags_added = added_tags;
            }
        }
    }
    Ok(result)
}

fn generate_sitemap(out_dir: &Path, chunks: &[String]) -> String {
    let mut urls = vec!["  <url><loc>/</loc><changefreq>daily</changefreq><priority>1.0</priority></url>".to_string()];
    for chunk in chunks {
        if chunk.ends_with(".html") {
            let path = chunk.trim_end_matches(".html");
            if !path.is_empty() {
                urls.push(format!("  <url><loc>/{}</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>", path));
            }
        }
    }
    format!("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n{}\n</urlset>", urls.join("\n"))
}

fn inject_meta_tags(html: &str) -> (String, Vec<String>) {
    let mut tags = Vec::new();
    let mut result = html.to_string();
    if !result.contains("name=\"viewport\"") {
        tags.push(r#"<meta name="viewport" content="width=device-width, initial-scale=1.0" />"#.to_string());
    }
    if !result.contains("name=\"description\"") {
        tags.push(r#"<meta name="description" content="Built with Pledgepack" />"#.to_string());
    }
    if !result.contains("charset=") {
        tags.push(r#"<meta charset="UTF-8" />"#.to_string());
    }
    if !tags.is_empty() {
        let injection = format!("\n{}\n", tags.join("\n"));
        if let Some(pos) = result.find("</head>") {
            result.insert_str(pos, &injection);
        } else {
            result = format!("{}\n{}", tags.join("\n"), result);
        }
    }
    (result, tags)
}

// ─── 119: Conditional exports resolution ──────────────────────────────

pub fn resolve_conditional_exports(
    exports: &serde_json::Value,
    subpath: Option<&str>,
    conditions: &[String],
    pkg_dir: &Path,
) -> Option<std::path::PathBuf> {
    let target_key = subpath.unwrap_or(".");
    if let Some(obj) = exports.as_object() {
        if obj.contains_key("import") || obj.contains_key("require") || obj.contains_key("default") {
            if target_key == "." {
                return resolve_conditions_custom(obj, conditions, pkg_dir);
            }
        }
        for (key, value) in obj {
            if key == target_key || matches_pattern(key, target_key) {
                if let Some(obj2) = value.as_object() {
                    if let Some(p) = resolve_conditions_custom(obj2, conditions, pkg_dir) {
                        return Some(p);
                    }
                } else if let Some(path) = value.as_str() {
                    let resolved = pkg_dir.join(path);
                    if resolved.is_file() {
                        return Some(resolved.canonicalize().unwrap_or(resolved));
                    }
                }
            }
        }
    } else if let Some(path) = exports.as_str() {
        if target_key == "." {
            let resolved = pkg_dir.join(path);
            if resolved.is_file() {
                return Some(resolved.canonicalize().unwrap_or(resolved));
            }
        }
    }
    None
}

fn resolve_conditions_custom(
    obj: &serde_json::Map<String, serde_json::Value>,
    conditions: &[String],
    pkg_dir: &Path,
) -> Option<std::path::PathBuf> {
    let mut all = conditions.to_vec();
    for d in &["browser", "import", "module", "require", "default"] {
        let s = d.to_string();
        if !all.contains(&s) { all.push(s); }
    }
    for condition in &all {
        if let Some(value) = obj.get(condition) {
            if let Some(path) = value.as_str() {
                let resolved = pkg_dir.join(path);
                if resolved.is_file() {
                    return Some(resolved.canonicalize().unwrap_or(resolved));
                }
            }
        }
    }
    None
}

fn matches_pattern(key: &str, target: &str) -> bool {
    if key.contains('*') {
        let parts: Vec<&str> = key.split('*').collect();
        if parts.len() == 2 {
            return target.starts_with(parts[0]) && target.ends_with(parts[1]);
        }
    }
    false
}

// ─── 120: Build concurrency control ───────────────────────────────────

pub fn determine_parallelism(configured: Option<usize>) -> usize {
    if let Some(n) = configured {
        if n > 0 { return n; }
    }
    let cores = std::thread::available_parallelism().map(|n| n.get()).unwrap_or(4);
    cores.min(16)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_web_component() {
        let src = "export function MyButton() {\n  return <button className=\"btn\">Click</button>;\n}";
        let r = compile_web_component(src, "src/MyButton.wc.tsx").unwrap();
        assert!(r.contains("class MyButton extends HTMLElement"));
        assert!(r.contains("customElements.define('my-button'"));
    }

    #[test]
    fn test_is_wc_file() {
        assert!(is_web_component_file("src/B.wc.tsx"));
        assert!(!is_web_component_file("src/B.tsx"));
    }

    #[test]
    fn test_federation_host() {
        let mut m = HashMap::new();
        m.insert("app1".to_string(), "http://cdn/app1.js".to_string());
        let cfg = FederationConfig { name: "h".into(), remotes: m, exposes: HashMap::new(),
            shared: vec![SharedModule { name: "react".into(), required_version: Some("^18".into()), eager: false, singleton: true }] };
        let b = generate_federation_host_bootstrap(&cfg);
        assert!(b.contains("__pledge_federation__"));
        assert!(b.contains("singleton: true"));
    }

    #[test]
    fn test_graphql_codegen() {
        let schema = "type User {\n  id: ID!\n  name: String!\n  email: String\n}\ntype Query {\n  user(id: ID!): User\n}\n";
        let cfg = GraphqlCodegenConfig { schema: "s.gql".into(), output: "out".into(), typescript: true, react_hooks: true };
        let t = generate_graphql_types(schema, &cfg).unwrap();
        assert!(t.contains("export interface User"));
        assert!(t.contains("id: string"));
        assert!(t.contains("email: string | null"));
        assert!(t.contains("useUser"));
    }

    #[test]
    fn test_load_env() {
        let d = std::env::temp_dir();
        let p = d.join(".env.test_pledge");
        std::fs::write(&p, "NODE_ENV=staging\nAPI_URL=https://stg.example.com\n").unwrap();
        let v = load_env_file(&d, "test_pledge");
        assert_eq!(v.get("NODE_ENV"), Some(&"staging".to_string()));
        std::fs::remove_file(&p).ok();
    }

    #[test]
    fn test_resolve_node_env() {
        let v = HashMap::new();
        assert_eq!(resolve_node_env(&v, true), "production");
        assert_eq!(resolve_node_env(&v, false), "development");
        let mut v2 = HashMap::new();
        v2.insert("NODE_ENV".to_string(), "staging".to_string());
        assert_eq!(resolve_node_env(&v2, true), "staging");
    }

    #[test]
    fn test_conditional_exports() {
        let exports = serde_json::json!({
            ".": {
                "production": "./dist/prod.js",
                "development": "./dist/dev.js",
                "default": "./dist/index.js"
            }
        });
        let dir = std::env::temp_dir();
        // Test with production condition
        let result = resolve_conditional_exports(&exports, None, &["production".to_string()], &dir);
        // Won't find file but should attempt resolution
        assert!(result.is_none()); // files don't exist in temp
    }

    #[test]
    fn test_determine_parallelism() {
        assert_eq!(determine_parallelism(Some(8)), 8);
        assert_eq!(determine_parallelism(Some(0)), std::thread::available_parallelism().map(|n| n.get()).unwrap_or(4).min(16));
        let auto = determine_parallelism(None);
        assert!(auto > 0 && auto <= 16);
    }

    #[test]
    fn test_sitemap_generation() {
        let ctx = PostBuildContext {
            out_dir: std::env::temp_dir(),
            html_path: None,
            chunks: vec!["index.html".to_string(), "about.html".to_string()],
            assets: vec![],
        };
        let sitemap = generate_sitemap(&ctx.out_dir, &ctx.chunks);
        assert!(sitemap.contains("<urlset"));
        assert!(sitemap.contains("<loc>/</loc>"));
    }
}
