// Edge-ready output — generate edge-function-compatible bundles
//
// Supports generating output for:
//   - Cloudflare Workers (Service Worker format)
//   - Vercel Edge Functions
//   - Deno Deploy
//
// Each format wraps the single-file bundle in the appropriate entry point format.

use anyhow::Result;
use std::path::Path;
use tracing::info;

/// Edge deployment target
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EdgeTarget {
    Cloudflare,
    Vercel,
    Deno,
}

impl EdgeTarget {
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "cloudflare" | "cf" | "workers" => Some(Self::Cloudflare),
            "vercel" | "edge" => Some(Self::Vercel),
            "deno" => Some(Self::Deno),
            _ => None,
        }
    }

    pub fn file_extension(&self) -> &str {
        match self {
            Self::Cloudflare => "js",
            Self::Vercel => "js",
            Self::Deno => "ts",
        }
    }

    pub fn output_filename(&self) -> &str {
        match self {
            Self::Cloudflare => "worker.js",
            Self::Vercel => "edge.js",
            Self::Deno => "mod.ts",
        }
    }
}

/// Generate an edge-compatible bundle from the single-file bundle content
pub fn generate_edge_bundle(
    target: EdgeTarget,
    bundle_code: &str,
    css_code: Option<&str>,
    out_dir: &Path,
) -> Result<()> {
    let output = match target {
        EdgeTarget::Cloudflare => generate_cloudflare_worker(bundle_code, css_code),
        EdgeTarget::Vercel => generate_vercel_edge(bundle_code, css_code),
        EdgeTarget::Deno => generate_deno_deploy(bundle_code, css_code),
    };

    let filename = target.output_filename();
    let output_path = out_dir.join(filename);
    std::fs::write(&output_path, &output)?;

    info!("Generated {} edge bundle: {}", target_name(target), output_path.display());

    // Generate deployment config files
    match target {
        EdgeTarget::Cloudflare => {
            let wrangler = r#"{
  "name": "pledge-app",
  "version": "0.0.1",
  "main": "worker.js",
  "compatibility_date": "2024-01-01"
}
"#;
            std::fs::write(out_dir.join("wrangler.toml"), wrangler)?;
        }
        EdgeTarget::Vercel => {
            let vercel_json = r#"{
  "version": 2,
  "functions": {
    "edge.js": { "runtime": "@vercel/edge" }
  }
}
"#;
            std::fs::write(out_dir.join("vercel.json"), vercel_json)?;
        }
        EdgeTarget::Deno => {
            // Deno doesn't need a config file, just deno.json for import map
            let deno_json = r#"{
  "tasks": {
    "start": "deno run --allow-net mod.ts"
  }
}
"#;
            std::fs::write(out_dir.join("deno.json"), deno_json)?;
        }
    }

    Ok(())
}

/// Generate Cloudflare Workers format
fn generate_cloudflare_worker(bundle_code: &str, css_code: Option<&str>) -> String {
    let css_injection = css_code
        .map(|css| format!(
            r#"
const PLEDGE_CSS = `{}`;
"#,
            css.replace('`', "\\`")
        ))
        .unwrap_or_default();

    format!(
        r#"// Pledge → Cloudflare Workers bundle
// Generated by pledge build --edge cloudflare
{}
const htmlTemplate = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Pledge App</title>{}</head>
<body><div id="root"></div><script type="module">{}</script></body></html>`;

export default {{
  async fetch(request, env, ctx) {{
    const url = new URL(request.url);

    // Serve the app shell for all routes (SPA mode)
    return new Response(htmlTemplate, {{
      headers: {{
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-cache',
      }},
    }});
  }},
}};
"#,
        css_injection,
        if css_code.is_some() { r#"<style id="__pledge_css"></style>"# } else { "" },
        bundle_code,
    )
}

/// Generate Vercel Edge Function format
fn generate_vercel_edge(bundle_code: &str, css_code: Option<&str>) -> String {
    let css_injection = css_code
        .map(|css| format!(
            r#"
const PLEDGE_CSS = `{}`;
"#,
            css.replace('`', "\\`")
        ))
        .unwrap_or_default();

    format!(
        r#"// Pledge → Vercel Edge Function bundle
// Generated by pledge build --edge vercel
{}
const htmlTemplate = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Pledge App</title>{}</head>
<body><div id="root"></div><script type="module">{}</script></body></html>`;

export const config = {{
  runtime: 'edge',
}};

export default async function handler(request) {{
  return new Response(htmlTemplate, {{
    headers: {{
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-cache',
    }},
  }});
}}
"#,
        css_injection,
        if css_code.is_some() { r#"<style id="__pledge_css"></style>"# } else { "" },
        bundle_code,
    )
}

/// Generate Deno Deploy format
fn generate_deno_deploy(bundle_code: &str, css_code: Option<&str>) -> String {
    let css_injection = css_code
        .map(|css| format!(
            r#"
const PLEDGE_CSS = `{}`;
"#,
            css.replace('`', "\\`")
        ))
        .unwrap_or_default();

    format!(
        r#"// Pledge → Deno Deploy bundle
// Generated by pledge build --edge deno
{}
const htmlTemplate = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Pledge App</title>{}</head>
<body><div id="root"></div><script type="module">{}</script></body></html>`;

Deno.serve(async (request) => {{
  return new Response(htmlTemplate, {{
    headers: {{
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-cache',
    }},
  }});
}});
"#,
        css_injection,
        if css_code.is_some() { r#"<style id="__pledge_css"></style>"# } else { "" },
        bundle_code,
    )
}

fn target_name(target: EdgeTarget) -> &'static str {
    match target {
        EdgeTarget::Cloudflare => "Cloudflare Workers",
        EdgeTarget::Vercel => "Vercel Edge",
        EdgeTarget::Deno => "Deno Deploy",
    }
}
