// Type-safe plugin API — TypeScript types for PledgePack plugins (#74)
//
// Generates and publishes TypeScript declaration files for the plugin API
// as the `pledgepack/plugins` entry point.
//
// Provides:
//   - Plugin interface with hook signatures
//   - Hook parameter and return types
//   - PluginContext type
//   - ServerContext for configureServer
//   - Rollup-compatible types for ecosystem compatibility

use anyhow::Result;
use std::path::Path;

/// Generate the TypeScript declaration file for the plugin API
pub fn generate_plugin_types() -> String {
    r#"// Type-safe plugin API for PledgePack
// Published as `pledgepack/plugins` entry point
// Generated by PledgePack — do not edit manually.

// ─── Plugin Interface ────────────────────────────────────────────────────────

/**
 * A PledgePack plugin. Plugins can hook into any stage of the build pipeline.
 *
 * @example
 * ```ts
 * import type { Plugin } from "pledgepack/plugins";
 *
 * const myPlugin: Plugin = {
 *   name: "my-plugin",
 *   transform(code, id) {
 *     return { code: code.toUpperCase(), map: null };
 *   },
 * };
 * export default myPlugin;
 * ```
 */
export interface Plugin {
  /** Plugin name — must be unique */
  name: string;

  /** Custom import resolution. Return resolved path or null for default. */
  resolveId?: (source: string, importer: string | undefined) => ResolveIdResult | Promise<ResolveIdResult>;

  /** Custom file loading. Return { code, map } or null for default loader. */
  load?: (id: string) => LoadResult | Promise<LoadResult>;

  /** Transform module source code. Return { code, map } or null to skip. */
  transform?: (code: string, id: string) => TransformResult | Promise<TransformResult>;

  /** Transform index.html. Return modified html, tags array, or { html, tags }. */
  transformIndexHtml?: (html: string) => TransformHtmlResult | TransformHtmlResult[];

  /** Configure dev server — add middleware, listen to events. */
  configureServer?: (server: ServerContext) => void | Promise<void>;

  /** Called when build starts. */
  buildStart?: () => void | Promise<void>;

  /** Called when build completes. */
  buildEnd?: (error?: Error) => void | Promise<void>;

  /** Called before bundle is emitted to disk. */
  generateBundle?: (opts: GenerateBundleOptions, bundle: Bundle) => void | Promise<void>;
}

// ─── Hook Return Types ───────────────────────────────────────────────────────

export type ResolveIdResult = string | null | { id: string; external?: boolean };

export type LoadResult = { code: string; map?: SourceMap | null } | null;

export type TransformResult = { code: string; map?: SourceMap | null } | null;

export type TransformHtmlResult = string | HtmlTagDescriptor | { html: string; tags: HtmlTagDescriptor[] };

// ─── Supporting Types ────────────────────────────────────────────────────────

export interface SourceMap {
  version: number;
  sources: string[];
  sourcesContent?: (string | null)[];
  names: string[];
  mappings: string;
  file?: string;
}

export interface HtmlTagDescriptor {
  tag: string;
  attrs?: Record<string, string | boolean>;
  children?: string | HtmlTagDescriptor[];
  injectTo?: "head" | "body" | "head-prepend" | "body-prepend";
}

export interface ServerContext {
  /** Add Express-style middleware to the dev server */
  use: (middleware: Middleware) => void;

  /** Listen to server events */
  on: (event: ServerEvent, handler: (...args: any[]) => void) => void;

  /** Send HMR update to connected clients */
  send: (type: string, data: any) => void;

  /** Reload the page in all connected browsers */
  reload: () => void;

  /** Restart the dev server */
  restart: () => void;

  /** WebSocket server instance */
  ws: WebSocketServer;
}

export type Middleware = (req: any, res: any, next: (err?: Error) => void) => void;

export type ServerEvent = "connection" | "request" | "close" | "error" | "hmr:accept" | "hmr:invalidate";

export interface WebSocketServer {
  send: (type: string, data: any) => void;
  close: () => void;
}

export interface GenerateBundleOptions {
  dir: string;
  format: "esm" | "cjs" | "iife";
}

export interface Bundle {
  [fileName: string]: BundleAsset;
}

export interface BundleAsset {
  type: "asset" | "chunk";
  fileName: string;
  code?: string;
  source?: string | Uint8Array;
}

// ─── Plugin Context ──────────────────────────────────────────────────────────

export interface PluginContext {
  /** Resolve a module specifier to an absolute path */
  resolve: (specifier: string, importer?: string) => Promise<string | null>;

  /** Read a file from the filesystem */
  read: (path: string) => Promise<string>;

  /** Emit a warning */
  warn: (message: string, position?: number | { line: number; column: number }) => void;

  /** Emit an error */
  error: (message: string, position?: number | { line: number; column: number }) => void;

  /** Get the current module's metadata */
  getModuleInfo: (id: string) => ModuleInfo | null;
}

export interface ModuleInfo {
  id: string;
  code: string;
  importedIds: string[];
  importedBindings: string[];
  isEntry: boolean;
  isExternal: boolean;
}

// ─── Plugin Preset ───────────────────────────────────────────────────────────

/**
 * A plugin preset bundles multiple plugins with sensible defaults.
 */
export interface PluginPreset {
  name: string;
  plugins: Plugin[];
  description?: string;
}

// ─── Helper Functions ────────────────────────────────────────────────────────

/**
 * Define a plugin with full type safety.
 * @example
 * ```ts
 * import { definePlugin } from "pledgepack/plugins";
 *
 * export default definePlugin({
 *   name: "my-plugin",
 *   transform(code, id) {
 *     return { code: code.replace(/process\.env\.NODE_ENV/g, '"production"') };
 *   },
 * });
 * ```
 */
export function definePlugin(plugin: Plugin): Plugin {
  return plugin;
}

/**
 * Define a plugin preset.
 */
export function definePreset(preset: PluginPreset): PluginPreset {
  return preset;
}

// ─── Re-exports for Rollup compatibility ─────────────────────────────────────

export type { Plugin as RollupPlugin } from "./rollup-compat";
export type { PluginContext as RollupPluginContext } from "./rollup-compat";
"#.to_string()
}

/// Write the plugin type declarations to disk
pub fn write_plugin_types(output_dir: &Path) -> Result<()> {
    let types_dir = output_dir.join("plugins");
    std::fs::create_dir_all(&types_dir)?;

    // Main plugin types
    let plugin_dts = generate_plugin_types();
    std::fs::write(types_dir.join("index.d.ts"), plugin_dts)?;

    // Rollup compatibility shim
    let rollup_compat = r#"// Rollup-compatible plugin types
// Allows existing Rollup/Vite plugins to work with PledgePack

export interface Plugin {
  name: string;
  resolveId?: (source: string, importer: string | undefined) => string | null | Promise<string | null>;
  load?: (id: string) => { code: string; map?: any } | null | Promise<{ code: string; map?: any } | null>;
  transform?: (code: string, id: string) => { code: string; map?: any } | null | Promise<{ code: string; map?: any } | null>;
  buildStart?: () => void | Promise<void>;
  buildEnd?: (error?: Error) => void | Promise<void>;
  generateBundle?: (opts: any, bundle: any) => void | Promise<void>;
}

export interface PluginContext {
  resolve: (specifier: string, importer?: string) => Promise<string | null>;
  warn: (message: string) => void;
  error: (message: string) => void;
}
"#;
    std::fs::write(types_dir.join("rollup-compat.d.ts"), rollup_compat)?;

    // package.json for the plugins entry point
    let pkg_json = r#"{
  "name": "pledgepack/plugins",
  "types": "./index.d.ts",
  "main": "./index.d.ts"
}"#;
    std::fs::write(types_dir.join("package.json"), pkg_json)?;

    Ok(())
}
