// Plugin documentation generator — auto-generate API docs from plugin hooks (#69)
//
// Parses plugin source files for:
//   - Exported plugin name
//   - Hook function signatures
//   - JSDoc comments on hooks
//   - Type annotations
//
// Outputs markdown documentation

use anyhow::Result;

/// Parsed plugin documentation
#[derive(Debug, Clone)]
pub struct PluginDocs {
    pub name: String,
    pub description: String,
    pub hooks: Vec<HookDoc>,
}

/// Documentation for a single hook
#[derive(Debug, Clone)]
pub struct HookDoc {
    pub name: String,
    pub signature: String,
    pub description: String,
    pub params: Vec<ParamDoc>,
    pub returns: String,
    pub example: Option<String>,
}

/// Parameter documentation
#[derive(Debug, Clone)]
pub struct ParamDoc {
    pub name: String,
    pub type_annotation: String,
    pub description: String,
}

/// Generate markdown documentation for a plugin from its source
pub fn generate_plugin_docs(source: &str) -> Result<PluginDocs> {
    let name = extract_plugin_name(source).unwrap_or_else(|| "anonymous".to_string());
    let description = extract_plugin_description(source).unwrap_or_default();

    let hooks = parse_hooks(source);

    Ok(PluginDocs {
        name,
        description,
        hooks,
    })
}

/// Render plugin docs as markdown
pub fn render_markdown(docs: &PluginDocs) -> String {
    let mut md = String::new();

    md.push_str(&format!("# {}\n\n", docs.name));

    if !docs.description.is_empty() {
        md.push_str(&format!("{}\n\n", docs.description));
    }

    md.push_str("## Hooks\n\n");

    if docs.hooks.is_empty() {
        md.push_str("_No hooks defined._\n");
    } else {
        for hook in &docs.hooks {
            md.push_str(&format!("### `{}`\n\n", hook.name));

            if !hook.description.is_empty() {
                md.push_str(&format!("{}\n\n", hook.description));
            }

            md.push_str(&format!("**Signature:**\n```ts\n{}\n```\n\n", hook.signature));

            if !hook.params.is_empty() {
                md.push_str("**Parameters:**\n\n");
                md.push_str("| Name | Type | Description |\n");
                md.push_str("|------|------|-------------|\n");
                for p in &hook.params {
                    md.push_str(&format!("| `{}` | `{}` | {} |\n", p.name, p.type_annotation, p.description));
                }
                md.push('\n');
            }

            if !hook.returns.is_empty() {
                md.push_str(&format!("**Returns:** `{}`\n\n", hook.returns));
            }

            if let Some(ref example) = hook.example {
                md.push_str("**Example:**\n```ts\n");
                md.push_str(example);
                md.push_str("\n```\n\n");
            }

            md.push_str("---\n\n");
        }
    }

    md.push_str(&format!(
        "_Generated by `pledge plugin docs` — PledgePack v{}_\n",
        env!("CARGO_PKG_VERSION")
    ));

    md
}

/// Extract plugin name from source (name: "..." or name: '...')
fn extract_plugin_name(source: &str) -> Option<String> {
    for quote in ['"', '\''] {
        let pattern = "name:";
        if let Some(pos) = source.find(pattern) {
            let rest = &source[pos + pattern.len()..];
            let trimmed = rest.trim_start();
            if trimmed.starts_with(quote) {
                let start = 1;
                if let Some(end) = trimmed[start..].find(quote) {
                    return Some(trimmed[start..start + end].to_string());
                }
            }
        }
    }
    None
}

/// Extract plugin description from JSDoc before export default
fn extract_plugin_description(source: &str) -> Option<String> {
    // Look for /** ... */ before export default
    let export_pos = source.find("export default")?;
    let before = &source[..export_pos];

    // Find the last /** ... */ block
    let last_doc_start = before.rfind("/**")?;
    let last_doc_end = before[last_doc_start..].find("*/")?;
    let doc_block = &before[last_doc_start + 3..last_doc_start + last_doc_end];

    // Extract description from JSDoc (first non-tag lines)
    let lines: Vec<&str> = doc_block
        .lines()
        .map(|l| l.trim().trim_start_matches('*').trim())
        .filter(|l| !l.is_empty() && !l.starts_with('@'))
        .collect();

    if lines.is_empty() {
        None
    } else {
        Some(lines.join(" "))
    }
}

/// Parse all hooks from plugin source
fn parse_hooks(source: &str) -> Vec<HookDoc> {
    let hook_names = [
        "resolveId",
        "load",
        "transform",
        "transformIndexHtml",
        "configureServer",
        "buildStart",
        "buildEnd",
        "generateBundle",
    ];

    let mut hooks = Vec::new();

    for hook_name in &hook_names {
        if let Some(hook_doc) = parse_hook(source, hook_name) {
            hooks.push(hook_doc);
        }
    }

    hooks
}

/// Parse a single hook from source
fn parse_hook(source: &str, hook_name: &str) -> Option<HookDoc> {
    // Find the hook definition: `hookName(` or `hookName: function` or `hookName: async`
    let patterns = [
        format!("{}(", hook_name),
        format!("{}:", hook_name),
        format!("{} :", hook_name),
    ];

    let mut hook_pos = None;
    for pattern in &patterns {
        if let Some(pos) = source.find(pattern) {
            hook_pos = Some(pos);
            break;
        }
    }

    let pos = hook_pos?;

    // Look for JSDoc comment before the hook
    let before = &source[..pos];
    let (description, params, returns, example) = parse_jsdoc(before);

    // Extract the function signature
    let after = &source[pos..];
    let signature = extract_signature(after, hook_name);

    // Extract params from signature if JSDoc didn't provide them
    let final_params = if params.is_empty() {
        extract_params_from_signature(&signature)
    } else {
        params
    };

    Some(HookDoc {
        name: hook_name.to_string(),
        signature,
        description,
        params: final_params,
        returns,
        example,
    })
}

/// Parse JSDoc comment from text before a hook
fn parse_jsdoc(before: &str) -> (String, Vec<ParamDoc>, String, Option<String>) {
    let mut description = String::new();
    let mut params = Vec::new();
    let mut returns = String::new();
    let mut example: Option<String> = None;

    if let Some(doc_start) = before.rfind("/**") {
        if let Some(doc_end) = before[doc_start..].find("*/") {
            let doc = &before[doc_start + 3..doc_start + doc_end];

            let mut in_example = false;
            for line in doc.lines() {
                let trimmed = line.trim().trim_start_matches('*').trim();

                if in_example {
                    if trimmed.is_empty() {
                        in_example = false;
                    } else {
                        example = Some(match &example {
                            Some(e) => format!("{}\n{}", e, trimmed),
                            None => trimmed.to_string(),
                        });
                    }
                    continue;
                }

                if trimmed.starts_with("@param") {
                    // @param {Type} name description
                    let rest = trimmed.strip_prefix("@param").unwrap_or("").trim();
                    let param = parse_jsdoc_param(rest);
                    params.push(param);
                } else if trimmed.starts_with("@returns") || trimmed.starts_with("@return") {
                    let rest = trimmed
                        .strip_prefix("@returns")
                        .or_else(|| trimmed.strip_prefix("@return"))
                        .unwrap_or("")
                        .trim();
                    if let Some(start) = rest.find('{') {
                        if let Some(end) = rest[start..].find('}') {
                            returns = rest[start + 1..start + end].to_string();
                        }
                    }
                } else if trimmed.starts_with("@example") {
                    in_example = true;
                } else if !trimmed.is_empty() && !trimmed.starts_with('@') {
                    if description.is_empty() {
                        description = trimmed.to_string();
                    } else {
                        description.push(' ');
                        description.push_str(trimmed);
                    }
                }
            }
        }
    }

    (description, params, returns, example)
}

/// Parse a single @param from JSDoc
fn parse_jsdoc_param(rest: &str) -> ParamDoc {
    let name;
    let mut type_annotation = String::new();
    let mut description = String::new();

    let mut rest = rest.trim();

    // Extract {Type}
    if rest.starts_with('{') {
        if let Some(end) = rest.find('}') {
            type_annotation = rest[1..end].to_string();
            rest = rest[end + 1..].trim();
        }
    }

    // Extract name (first word, may be prefixed with [ ] for optional)
    if let Some(space) = rest.find(char::is_whitespace) {
        name = rest[..space].trim_matches(|c| c == '[' || c == ']').to_string();
        description = rest[space..].trim().to_string();
    } else {
        name = rest.trim_matches(|c| c == '[' || c == ']').to_string();
    }

    ParamDoc {
        name,
        type_annotation,
        description,
    }
}

/// Extract function signature from source
fn extract_signature(source: &str, hook_name: &str) -> String {
    // Find the opening paren
    let paren_pos = match source.find('(') {
        Some(p) => p,
        None => return format!("{}()", hook_name),
    };

    // Find matching close paren
    let mut depth = 0;
    let mut end = paren_pos;
    for (i, c) in source[paren_pos..].char_indices() {
        match c {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    end = paren_pos + i;
                    break;
                }
            }
            _ => {}
        }
    }

    let params = &source[paren_pos + 1..end];

    // Check if async
    let is_async = source[..paren_pos].contains("async");

    let prefix = if is_async { "async " } else { "" };

    format!("{}{}({})", prefix, hook_name, params)
}

/// Extract parameters from function signature
fn extract_params_from_signature(signature: &str) -> Vec<ParamDoc> {
    let start = match signature.find('(') {
        Some(s) => s + 1,
        None => return Vec::new(),
    };
    let end = match signature.rfind(')') {
        Some(e) => e,
        None => return Vec::new(),
    };

    let params_str = &signature[start..end];
    if params_str.trim().is_empty() {
        return Vec::new();
    }

    params_str
        .split(',')
        .map(|p| {
            let p = p.trim();
            let parts: Vec<&str> = p.splitn(2, ':').collect();
            let name = parts[0].trim().to_string();
            let type_annotation = parts.get(1).map(|t| t.trim().to_string()).unwrap_or_default();
            ParamDoc {
                name,
                type_annotation,
                description: String::new(),
            }
        })
        .collect()
}
