// Plugin template generator — `pledge create plugin` scaffolds a new plugin (#68)
//
// Generates:
//   - Plugin entry file (index.js) with hook signatures
//   - pledge.config.ts for the plugin itself
//   - test/ directory with a basic test file
//   - README.md with usage instructions
//   - package.json with plugin metadata

use anyhow::Result;
use std::path::Path;

/// Plugin template options
#[derive(Debug, Clone)]
pub struct PluginTemplateOptions {
    pub name: String,
    pub description: String,
    pub author: String,
    pub hooks: Vec<PluginHook>,
}

/// Available plugin hooks
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PluginHook {
    ResolveId,
    Load,
    Transform,
    TransformIndexHtml,
    ConfigureServer,
    BuildStart,
    BuildEnd,
    GenerateBundle,
}

impl PluginHook {
    pub fn all() -> Vec<PluginHook> {
        vec![
            PluginHook::ResolveId,
            PluginHook::Load,
            PluginHook::Transform,
            PluginHook::TransformIndexHtml,
            PluginHook::ConfigureServer,
            PluginHook::BuildStart,
            PluginHook::BuildEnd,
            PluginHook::GenerateBundle,
        ]
    }

    pub fn name(&self) -> &'static str {
        match self {
            PluginHook::ResolveId => "resolveId",
            PluginHook::Load => "load",
            PluginHook::Transform => "transform",
            PluginHook::TransformIndexHtml => "transformIndexHtml",
            PluginHook::ConfigureServer => "configureServer",
            PluginHook::BuildStart => "buildStart",
            PluginHook::BuildEnd => "buildEnd",
            PluginHook::GenerateBundle => "generateBundle",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            PluginHook::ResolveId => "Custom import resolution",
            PluginHook::Load => "Custom file loading",
            PluginHook::Transform => "Transform module source code",
            PluginHook::TransformIndexHtml => "Transform index.html",
            PluginHook::ConfigureServer => "Configure dev server middleware",
            PluginHook::BuildStart => "Called at build start",
            PluginHook::BuildEnd => "Called at build end",
            PluginHook::GenerateBundle => "Called before bundle emit",
        }
    }
}

/// Scaffold a new plugin project
pub fn scaffold_plugin(opts: &PluginTemplateOptions, out_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(out_dir)?;

    // package.json
    let pkg_json = format!(r#"{{
  "name": "{}",
  "version": "0.0.1",
  "description": "{}",
  "main": "index.js",
  "author": "{}",
  "license": "MIT",
  "keywords": ["pledgepack", "pledgepack-plugin"],
  "files": ["index.js", "pledge.config.ts"]
}}
"#, opts.name, opts.description, opts.author);
    std::fs::write(out_dir.join("package.json"), pkg_json)?;

    // index.js — plugin entry with hook stubs
    let hooks_code = generate_hooks_code(&opts.hooks);
    let index_js = format!(r#"// {name} — PledgePack plugin
// {description}
//
// Generated by `pledge create plugin`

/**
 * @type {{PledgePackPlugin}}
 */
export default {{
  name: "{name}",

{hooks}
}};
"#, name = opts.name, description = opts.description, hooks = hooks_code);
    std::fs::write(out_dir.join("index.js"), index_js)?;

    // pledge.config.ts for the plugin itself
    let config = format!(r#"// PledgePack config for {name} plugin development
import {{ defineConfig }} from "pledgepack/config";

export default defineConfig({{
  entry: ["test/fixture.tsx"],
  plugins: ["./index.js"],
  devServer: {{
    port: 3100,
  }},
}});
"#, name = opts.name);
    std::fs::write(out_dir.join("pledge.config.ts"), config)?;

    // test/ directory
    let test_dir = out_dir.join("test");
    std::fs::create_dir_all(&test_dir)?;

    let test_file = format!(r#"// Test file for {name} plugin
// Run with: pledge test

import {{ expect, it }} from "vitest";
import plugin from "../index.js";

it("plugin has correct name", () => {{
  expect(plugin.name).toBe("{name}");
}});

it("plugin has hooks defined", () => {{
  expect(plugin).toBeDefined();
}});
"#, name = opts.name);
    std::fs::write(test_dir.join("plugin.test.ts"), test_file)?;

    // test/fixture.tsx — minimal fixture for dev testing
    let fixture = r#"// Minimal fixture for plugin development
export function App() {
  return <div>Hello from fixture</div>;
}
"#;
    std::fs::write(test_dir.join("fixture.tsx"), fixture)?;

    // README.md
    let readme = format!(r#"# {name}

{description}

## Usage

```ts
// pledge.config.ts
import {{ defineConfig }} from "pledgepack/config";

export default defineConfig({{
  plugins: ["{name}"],
}});
```

## Hooks

{hooks_list}

## Development

```bash
pledge dev    # Start dev server with plugin
pledge test   # Run plugin tests
```

## License

MIT
"#,
        name = opts.name,
        description = opts.description,
        hooks_list = opts.hooks.iter().map(|h| format!("- **{}** — {}", h.name(), h.description())).collect::<Vec<_>>().join("\n")
    );
    std::fs::write(out_dir.join("README.md"), readme)?;

    // .gitignore
    std::fs::write(out_dir.join(".gitignore"), "node_modules/\n.pledge/\ndist/\n")?;

    Ok(())
}

/// Generate hook function stubs
fn generate_hooks_code(hooks: &[PluginHook]) -> String {
    hooks
        .iter()
        .map(|hook| {
            let (params, body) = match hook {
                PluginHook::ResolveId => (
                    "source, importer",
                    "    // Return resolved id or null to use default resolution\n    return null;",
                ),
                PluginHook::Load => (
                    "id",
                    "    // Return { code, map } or null to use default loader\n    return null;",
                ),
                PluginHook::Transform => (
                    "code, id",
                    "    // Return { code, map } or null to skip transform\n    return null;",
                ),
                PluginHook::TransformIndexHtml => (
                    "html",
                    "    // Return modified html string, array of tags, or { html, tags }\n    return html;",
                ),
                PluginHook::ConfigureServer => (
                    "server",
                    "    // server.use(middleware) to add middleware\n    // server.on(event, handler) to listen to events",
                ),
                PluginHook::BuildStart => (
                    "",
                    "    // Called when build starts",
                ),
                PluginHook::BuildEnd => (
                    "",
                    "    // Called when build completes",
                ),
                PluginHook::GenerateBundle => (
                    "",
                    "    // Called before bundle is emitted to disk",
                ),
            };
            format!(
                "  {name}({params}) {{\n{body}\n  }}",
                name = hook.name(),
                params = params,
                body = body
            )
        })
        .collect::<Vec<_>>()
        .join(",\n\n")
}
